on: [pull_request]

jobs:
  validate:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache PowerShell modules
      id: cacher
      uses: actions/cache@v4
      with:
        path: ~\Documents\WindowsPowerShell\Modules
        key: ps-modules-${{ runner.os }}-v1

    - name: Install Prerequisites
      if: steps.cacher.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
        $modules = @(
          'Pester',
          'PSFramework',
          'PSModuleDevelopment',
          'PSScriptAnalyzer',
          'ImportExcel',
          'Az.Accounts'
        )
        foreach ($module in $modules) {
          Write-Host "Installing $module..."
          Install-Module -Name $module -Scope CurrentUser -Force -SkipPublisherCheck
        }

    - name: Validate
      run: .\build\vsts-validate.ps1
      shell: powershell